M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Fri 27 Oct 2023 06:02:48 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-27T18:02:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.15Y-3.3469
X4.15Y-4.5969
X7.9Y-3.3469
X7.9Y-4.5969
T0
M30
